openapi: 3.0.0
info:
  version: 1.0.0
  title: Book Service API
  description: API for managing books in the book-service.

servers:
  - url: "localhost:8081"

paths:
  /books:
    post:
      summary: Add a new book
      requestBody:
        description: Book object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        201:
          description: Book added successfully
        400:
          description: Invalid input

    get:
      summary: Get all books
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        404:
          description: Books not found

  /books/{id}:
    get:
      summary: Get a book by its ID
      parameters:
        - name: id
          in: path
          description: ID of the book to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful retrieval of book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Book not found

    put:
      summary: Update a book by its ID
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Updated book object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        200:
          description: Book updated successfully
        400:
          description: Invalid input
        404:
          description: Book not found

    delete:
      summary: Delete a book by its ID
      parameters:
        - name: id
          in: path
          description: ID of the book to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Book deleted successfully
        404:
          description: Book not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        title:
          type: string
        author:
          type: string
        isbn:
          type: string
        yearPublished:
          type: integer
      required:
        - title
        - author
        - isbn
        - yearPublished
